### ISSUE TITLE
what`s the final_model

### ISSUE THREAD

**Issue by liupeng0518** [illidanlab/T-LSTM#3]
python main.py 1 "/research/prip-baytasin/Synth_EHR/Split0" 1e-3 50 1.0 128 64 "/research/prip-baytasin/T-LSTM-master/TLSTM/final_model"
when i run this command, what`s the **final_model**,thanks,could you give me a example？
thank you very much!

**Comment by baytasin** [comment]
Hi,
You could use the final_model for testing (training_mode is 0). For instance, if you are done with training and you need to test the model on different subsets , you can use the final model to load the learned parameters and directly see test performance instead of training all over again. 
Thank you.

**Comment by liupeng0518** [comment]
Ok Thank you!
